language: objective-c
osx_image: xcode8.2

script:
  - open -a "simulator" --args -CurrentDeviceUDID AD8E8C76-910E-437D-88C2-4D6F6EBE3355
  - xcodebuild clean build test -project SweetRouter.xcodeproj -scheme SweetRouter -destination 'platform=iOS Simulator,OS=10.2,id=AD8E8C76-910E-437D-88C2-4D6F6EBE3355'

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: true
